[tool.pytest.ini_options]
log_cli = true
log_file = "NeuralNetworkDebug.log"
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_file_format = "%(asctime)s [%(levelname)6s]: %(message)s (%(filename)s:%(lineno)s)"
log_file_date_format = "%Y-%m-%d %I:%M:%S %p"
